sudo: required
services:
  - docker

# Runs before build
before_install:
  - docker build -t hammadjafar/docker -f Dockerfile.dev .

script: 
  - docker run --rm -e CI=true hammadjafar/docker npm test -- --coverage --watchAll=false
