sudo: required
services:
  - docker

# Runs  before build
before_install:
  - docker build -t hammadjafar/docker -f Dockerfile.dev .

script: 
  - docker run --rm -e CI=true hammadjafar/docker npm test -- --coverage --watchAll=false

# deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#  bucket_path: "docker"
#  on:
#     branch: master